import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, MapPin } from "lucide-react";
import { statistics } from "@/data/mock";
import { ProblemMap } from "@/components/samarth/problem-map";
import { LandingExperience } from "@/components/samarth/landing-experience";

const journey = [["01", "Report", "Citizens describe a local need in their own words."], ["02", "Structure", "AI turns the signal into a clear, usable challenge."], ["03", "Validate", "People verify evidence, location and urgency."], ["04", "Match", "Institutions connect by capability and proximity."], ["05", "Build", "Faculty and student teams turn a brief into action."], ["06", "Measure", "Outcomes stay visible long after deployment."]];

export default function Home() { return <LandingExperience><main>
  <nav className="mx-auto flex max-w-[1440px] items-center justify-between border-b border-border px-5 py-5 md:px-10"><Link href="/" className="font-mono text-sm font-medium tracking-[.2em]">SAMARTH</Link><div className="hidden gap-7 text-xs uppercase tracking-[.13em] md:flex"><a href="#platform">Platform</a><a href="#how">How it works</a><Link href="/map">Network</Link><a href="#impact">Impact</a></div><div className="flex items-center gap-4 text-xs font-semibold uppercase tracking-[.1em]"><Link className="hidden sm:block" href="/map">Explore problems</Link><Link className="border border-foreground px-4 py-2.5" href="/auth/login">Enter Samarth</Link></div></nav>
  <section className="relative mx-auto max-w-[1440px] overflow-hidden px-5 pb-24 pt-20 md:px-10 md:pb-36 md:pt-28"><div className="absolute right-[-12%] top-10 h-[90%] w-[55%] border border-border opacity-70 [clip-path:polygon(41%_0,63%_10%,84%_29%,72%_57%,89%_83%,46%_100%,17%_74%,3%_44%,20%_17%)]"/><div className="relative max-w-5xl"><p className="eyebrow">Community · institutions · impact</p><h1 className="editorial mt-7 text-6xl leading-[.9] md:text-8xl lg:text-[8.5rem]">Problems people face.<br/>Solutions people build.</h1><p className="mt-9 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">Samarth turns real-world community needs into structured, trackable challenges—and connects them with institutions and teams capable of solving them.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="bg-foreground px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-background" href="/auth/login">Explore Samarth <ArrowDownRight className="ml-2 inline" size={15}/></Link><Link className="border border-foreground px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em]" href="/map">Explore problems <ArrowUpRight className="ml-2 inline" size={15}/></Link></div></div><div className="relative mt-20 grid border-y border-border sm:grid-cols-4">{statistics.map((stat) => <div key={stat.label} className="border-b border-border py-5 sm:border-b-0 sm:border-r sm:px-5 last:border-r-0"><b className="editorial block text-4xl tracking-[-.04em]">{stat.value}</b><span className="eyebrow mt-2 block text-muted-foreground">{stat.label}</span></div>)}</div></section>
  <section id="how" className="border-y border-border bg-[var(--background)] px-5 py-20 md:px-10"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 md:grid-cols-2"><p className="eyebrow">The lifecycle</p><h2 className="editorial max-w-xl text-4xl leading-none md:text-6xl">One shared path from a local voice to measurable change.</h2></div><div className="mt-16 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-3">{journey.map(([number,title,copy]) => <article key={number} className="min-h-48 border-b border-r border-border p-5"><span className="eyebrow text-muted-foreground">{number}</span><h3 className="editorial mt-10 text-3xl">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>
  <section id="platform" className="mx-auto grid max-w-[1440px] gap-10 px-5 py-24 md:grid-cols-[.75fr_1.25fr] md:px-10"><div><p className="eyebrow">Geographic intelligence</p><h2 className="editorial mt-5 text-5xl leading-[.95]">See what needs solving around you.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-muted-foreground">A living geographic view makes community need visible: density when you look wide, human detail when you get close.</p><Link href="/map" className="mt-7 inline-block border-b border-foreground pb-1 text-xs font-bold uppercase tracking-[.12em]">Open the problem map →</Link></div><ProblemMap compact/></section>
  <section id="impact" className="border-t border-border bg-[#11110f] px-5 py-24 text-[#f7f7f4] md:px-10"><div className="mx-auto max-w-[1440px]"><p className="eyebrow text-[#bbbbae]">Built for visible impact</p><h2 className="editorial mt-6 max-w-4xl text-5xl leading-[.94] md:text-7xl">Every problem has a place.<br/>Every solution needs a team.</h2><div className="mt-12 flex flex-wrap gap-3"><Link href="/problems/new" className="bg-background px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-foreground">I have a problem</Link><Link href="/auth/login" className="border border-[#aaa99f] px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em]">For an institution</Link></div><p className="mt-16 flex items-center gap-2 font-mono text-xs text-[#bbbbae]"><MapPin size={14}/> Jharkhand community network · static prototype data</p></div></section>
</main></LandingExperience>; }
